[package]
name = "gametube"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
async-stream = "0.3.5"
enigo = "0.2.1"
env_logger = "0.11.5"
log = "0.4.22"
tokio = { version = "1.39.3", features = ["full"] }
