games:
    - slug: 3104840
      title: Mageanoid
      thumbnail: https://shared.steamstatic.com/store_item_assets/steam/apps/3104840/header.jpg?t=$NOW
      source: /Users/frank/Git/mageanoid/pack
      working_directory: /games/mageanoid/
      entrypoint: ./mageanoid
      save: $XDG_CONFIG_HOME/mageanoid/
